{"trial_id": "07", "hyperparameters": {"space": [{"class_name": "Boolean", "config": {"name": "structured_data_block_1/normalize", "default": false, "conditions": []}}, {"class_name": "Boolean", "config": {"name": "structured_data_block_1/dense_block_1/use_batchnorm", "default": false, "conditions": []}}, {"class_name": "Choice", "config": {"name": "structured_data_block_1/dense_block_1/num_layers", "default": 2, "conditions": [], "values": [1, 2, 3], "ordered": true}}, {"class_name": "Choice", "config": {"name": "structured_data_block_1/dense_block_1/units_0", "default": 32, "conditions": [], "values": [16, 32, 64, 128, 256, 512, 1024], "ordered": true}}, {"class_name": "Choice", "config": {"name": "structured_data_block_1/dense_block_1/dropout", "default": 0.0, "conditions": [], "values": [0.0, 0.25, 0.5], "ordered": true}}, {"class_name": "Choice", "config": {"name": "structured_data_block_1/dense_block_1/units_1", "default": 32, "conditions": [], "values": [16, 32, 64, 128, 256, 512, 1024], "ordered": true}}, {"class_name": "Choice", "config": {"name": "classification_head_1/dropout", "default": 0, "conditions": [], "values": [0.0, 0.25, 0.5], "ordered": true}}, {"class_name": "Choice", "config": {"name": "optimizer", "default": "adam", "conditions": [], "values": ["adam", "sgd", "adam_weight_decay"], "ordered": false}}, {"class_name": "Choice", "config": {"name": "learning_rate", "default": 0.001, "conditions": [], "values": [0.1, 0.01, 0.001, 0.0001, 2e-05, 1e-05], "ordered": true}}], "values": {"structured_data_block_1/normalize": true, "structured_data_block_1/dense_block_1/use_batchnorm": false, "structured_data_block_1/dense_block_1/num_layers": 2, "structured_data_block_1/dense_block_1/units_0": 32, "structured_data_block_1/dense_block_1/dropout": 0, "structured_data_block_1/dense_block_1/units_1": 32, "classification_head_1/dropout": 0.0, "optimizer": "adam_weight_decay", "learning_rate": 0.001}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"C:\\Users\\Eliezer\\anaconda3\\Lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 273, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"C:\\Users\\Eliezer\\anaconda3\\Lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 238, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Eliezer\\anaconda3\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Eliezer\\anaconda3\\Lib\\site-packages\\autokeras\\engine\\tuner.py\", line 101, in _build_and_fit_model\n    _, history = utils.fit_with_adaptive_batch_size(\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Eliezer\\anaconda3\\Lib\\site-packages\\autokeras\\utils\\utils.py\", line 88, in fit_with_adaptive_batch_size\n    history = run_with_adaptive_batch_size(\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Eliezer\\anaconda3\\Lib\\site-packages\\autokeras\\utils\\utils.py\", line 101, in run_with_adaptive_batch_size\n    history = func(x=x, validation_data=validation_data, **fit_kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Eliezer\\anaconda3\\Lib\\site-packages\\autokeras\\utils\\utils.py\", line 89, in <lambda>\n    batch_size, lambda **kwargs: model.fit(**kwargs), **fit_kwargs\n                                 ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Eliezer\\anaconda3\\Lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\Eliezer\\anaconda3\\Lib\\site-packages\\tensorflow\\python\\eager\\execute.py\", line 66, in quick_execute\n    except TypeError as e:\ntensorflow.python.framework.errors_impl.UnimplementedError: Graph execution error:\n\nDetected at node Adam/Cast_4 defined at (most recent call last):\n  File \"c:\\Users\\Eliezer\\Documents\\GitHub\\MY_DMU_IIP\\1_BP_NET\\nas.py\", line 35, in <module>\n\n  File \"C:\\Users\\Eliezer\\anaconda3\\Lib\\site-packages\\autokeras\\tasks\\structured_data.py\", line 326, in fit\n\n  File \"C:\\Users\\Eliezer\\anaconda3\\Lib\\site-packages\\autokeras\\tasks\\structured_data.py\", line 139, in fit\n\n  File \"C:\\Users\\Eliezer\\anaconda3\\Lib\\site-packages\\autokeras\\auto_model.py\", line 292, in fit\n\n  File \"C:\\Users\\Eliezer\\anaconda3\\Lib\\site-packages\\autokeras\\engine\\tuner.py\", line 193, in search\n\n  File \"C:\\Users\\Eliezer\\anaconda3\\Lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 233, in search\n\n  File \"C:\\Users\\Eliezer\\anaconda3\\Lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 273, in _try_run_and_update_trial\n\n  File \"C:\\Users\\Eliezer\\anaconda3\\Lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 238, in _run_and_update_trial\n\n  File \"C:\\Users\\Eliezer\\anaconda3\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n\n  File \"C:\\Users\\Eliezer\\anaconda3\\Lib\\site-packages\\autokeras\\engine\\tuner.py\", line 101, in _build_and_fit_model\n\n  File \"C:\\Users\\Eliezer\\anaconda3\\Lib\\site-packages\\autokeras\\utils\\utils.py\", line 88, in fit_with_adaptive_batch_size\n\n  File \"C:\\Users\\Eliezer\\anaconda3\\Lib\\site-packages\\autokeras\\utils\\utils.py\", line 101, in run_with_adaptive_batch_size\n\n  File \"C:\\Users\\Eliezer\\anaconda3\\Lib\\site-packages\\autokeras\\utils\\utils.py\", line 89, in <lambda>\n\n  File \"C:\\Users\\Eliezer\\anaconda3\\Lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 65, in error_handler\n\n  File \"C:\\Users\\Eliezer\\anaconda3\\Lib\\site-packages\\keras\\src\\engine\\training.py\", line 1783, in fit\n\n  File \"C:\\Users\\Eliezer\\anaconda3\\Lib\\site-packages\\keras\\src\\engine\\training.py\", line 1377, in train_function\n\n  File \"C:\\Users\\Eliezer\\anaconda3\\Lib\\site-packages\\keras\\src\\engine\\training.py\", line 1360, in step_function\n\n  File \"C:\\Users\\Eliezer\\anaconda3\\Lib\\site-packages\\keras\\src\\engine\\training.py\", line 1349, in run_step\n\n  File \"C:\\Users\\Eliezer\\anaconda3\\Lib\\site-packages\\keras\\src\\engine\\training.py\", line 1130, in train_step\n\n  File \"C:\\Users\\Eliezer\\anaconda3\\Lib\\site-packages\\keras\\src\\optimizers\\optimizer.py\", line 544, in minimize\n\n  File \"C:\\Users\\Eliezer\\anaconda3\\Lib\\site-packages\\autokeras\\keras_layers.py\", line 360, in apply_gradients\n\n  File \"C:\\Users\\Eliezer\\anaconda3\\Lib\\site-packages\\keras\\src\\optimizers\\optimizer.py\", line 1223, in apply_gradients\n\n  File \"C:\\Users\\Eliezer\\anaconda3\\Lib\\site-packages\\keras\\src\\optimizers\\optimizer.py\", line 650, in apply_gradients\n\n  File \"C:\\Users\\Eliezer\\anaconda3\\Lib\\site-packages\\keras\\src\\optimizers\\optimizer.py\", line 1242, in _apply_weight_decay\n\n  File \"C:\\Users\\Eliezer\\anaconda3\\Lib\\site-packages\\keras\\src\\optimizers\\optimizer.py\", line 1238, in distributed_apply_weight_decay\n\n  File \"C:\\Users\\Eliezer\\anaconda3\\Lib\\site-packages\\keras\\src\\optimizers\\optimizer.py\", line 1234, in weight_decay_fn\n\nCast string to float is not supported\n\t [[{{node Adam/Cast_4}}]] [Op:__inference_train_function_110846]\n"}